camunda/camunda-platform

- docker-compose.yaml
- 3.8.1 didn't startup in CCSM due to a bug https://jira.camunda.com/browse/OPT-6183
relates to #OPT-6183
> fix(optimize): update to 3.8.2

- docker-compose-core.yaml
To avoid the flood of warnings in the logs
closes #17
> disable security for ElasticSearch

- docker-compose.yaml
As done already for docker-compose-core, this setting will reduce the log size and supress all hints to insecure ElasticSearch connections for the second setup.
> Allow insecure connection to ElasticSearch

- docker-compose.yaml
To align with the Camunda Helm charts and also how Identity is used internally this PR updates the Keycloak image used to the Bitnami offering (which also requires a postgres container).
> fix: update keycloak image to align with Helm charts

- README.md
- connector-secrets.txt
- docker-compose-core.yaml
- docker-compose.yaml
- adds connectors bundle to the core and full distribution
- connectors bundle contains all out-of-the-box connectors for Camunda 8
- add connector-secrets.txt file to inject secrets into the environment
- update README with description of the connectors
closes #34
> Add connectors bundle

- README.md
- docker-compose-core.yaml
- docker-compose.yaml
This adds a `dev` profile to  `docker-compose.yaml`, and `docker-compose-core.yaml`, which spins up Kibana in addition to the other core components.
Kibana can be used to explore the records exported into Elasticsearch for troubleshooting or development purposes.
For a detailed tutorial, see https://github.com/camunda/zeebe/wiki/How-to-inspect-data-in-Elasticsearch
> Add Kibana to docker compose files along with `dev` profile

- docker-compose.yaml
this PR fixes the issue #37 by extending the health check
> fixes #37 - extended healthcheck for postgres to eliminate FATAL log statements

- README.md
- docker-compose-core.yaml
- docker-compose.yaml
We expect that users will use this project for development purposes only. For production usage, they should use our helm charts. However, a section was added to the README about development, which is likely confusing. This section was about using Kibana to inspect, explore or troubleshoot the camunda platform record log in Elasticsearch. It could however also be used to explore the data of the other components (Operate, Tasklist, Optimize).
- This renames the profile to `kibana` to better reflect the usage. 
- It also improves the README to better convey what this profile can be used for. 
- Lastly, it updates the note about index patterns, as this was very specific to 1 of the use cases that Kibana can be used for.
closes #51
> Rename dev profile to kibana

- docker-compose.yaml
With the update to Keycloak v19 in https://github.com/camunda/camunda-platform/pull/55 I have enabled the health endpoint according to https://github.com/camunda/camunda-platform/pull/55#discussion_r1010356644 which Keycloak now serves on the public port. According to [Keycloak docs](https://www.keycloak.org/server/reverseproxy) this endpoint should not be exposed publicly but rather protected by f.e. ingress path filtering. 
> Exposed health checks lead to an unnecessary attack vector.
This PR removes the exposure of health endpoint and just uses the `/auth` endpoint for checks
> chore: disable health endpoint for Keycloak

- README.md
This PR fixes the broken link in [README.md](https://github.com/camunda/camunda-platform/blob/88ecbb6f373751d18fff6b35e4d9cc47b7cb6506/README.md?plain=1#L81).
> docs: fix dead link

- .keycloak/Dockerfile
- README.md
Part of #21, Fixes https://github.com/camunda-cloud/identity/issues/1304
Provides a Dockerfile to build an arm64-based Keycloak image locally and respective documentation in the Readme.
Keycloak is an opensource project and there are multiple distributors providing docker images. We use Bitnami based image that are not available for arm64 yet [Ref](https://hub.docker.com/r/bitnami/keycloak/tags). There are Docker images for Keycloak 20.0+ available for arm at [hub.docker.com/r/keycloak/keycloak](https://hub.docker.com/r/keycloak/keycloak/tags) but these have different ENV variable naming and run configuration than the bitnami ones and are therefore not compatible with the docker-compose files included in this repository.
Although bitnami's …
> chore: add a Dockerfile for arm-based Keycloak

- docker-compose-web-modeler-beta.yaml
- Bumps Web Modeler version to `0.3.0-beta`
- Closes https://github.com/camunda/web-modeler/issues/3303
- Removes obsolete environment variables; see
- https://github.com/camunda/web-modeler/issues/3377
- https://github.com/camunda/web-modeler/issues/3375
> Web Modeler 0.3.0-beta

- docker-compose-core.yaml
- docker-compose.yaml
Since 0.16.1, connectors images are multiplatform.
> chore(connectors): bump connectors-bundle to 0.16.1

- docker-compose.yaml
I tried to spin up a setup with the latest 8.1.8 or 8.2.0-alpha4 and encountered the issue that `curl` was not available anymore in the identity image.
> fix(identity): use wget for healthcheck

- docker-compose-core.yaml
- docker-compose.yaml
In a customer call, I got the feedback that the effect of this configuration is unclear.
After going through the disclaimer of the docker-compose file, we agreed on adding a line with a short explanation.
> Clarify Bulk Size configuration in docker-compose

- README.md
Add language to encourage the first 2 development options, given we mention Docker compose (because the Docker compose file lives in this repo).
> docs(README): Emphasize dev options

- .env
- README.md
- docker-compose-web-modeler-beta.yaml
- docker-compose.yaml
This adds all the required config to run the stack with an authentication secured Zeebe GRPC API.
I went for leaving it disabled by default to lower the boundary of "playing around" as otherwise clients and web modeler require the credential setup.
closes #104
> feat(zeebe): authentication config zeebe gateway

- docker-compose-web-modeler-beta.yaml
Docker Compose part of https://github.com/camunda/web-modeler/issues/4284.
**Note**: The change will only become effective with the yet to-be-released 8.2 images of Web Modeler.
> chore(web-modeler): enable Zeebe Play

- docker-compose.yaml
Fixes a wrong variable name in Operate container. The wrong name made the resource authorizations flag being ignored in Operate and thus displaying all processes/decisions.
> fix: fix env variable name for Operate

- .github/workflows/release.yaml
that's embarrassing.
What happened here is that when we ran 
```
gh release edit ... $GITHUB_REF
```
`$GITHUB_REF` either gets populated with a full github reference (such as `refs/tags/8.3.0`) instead of `8.3.0`, or possibly an empty string because github actions is very inconsistent.  
GITHUB_REF_NAME is the proper value we should have been using, and the local shell script version already was referencing this.
> fix: variable is actually called GITHUB_REF_NAME

- .github/workflows/test-default.yaml
- .github/workflows/test-modeler.yaml
I want to set up branch protection, and it's complicating the github settings when the job names in my github actions are all the same.  This PR changes the names to be unique
> fix(ci): renames job names

- .github/renovate.json5
I've created this [repo](https://github.com/camunda/camunda-platform-renovate-test/issues)  to test running renovate on this repository. My primary motivation is to automate the process of updating CAMUNDA_PLATFORM_VERSION whenever `camunda/operate` puts out a release.  Since this version is synchronized across zeebe, identity, operate, and tasklist, and renovate configs can only look at one datasource, I just chose camunda/operate.   
The expected workflow if  operate publishes an image but  identity does not is that the CI will fail and maintainers of this repository will rerun the Github Actions after some time has past.
Including renovate does also come with the side effect that it might recommend updates for other parts of our repository too, such as our go.mod file for the release …
> feat(ci): renovate configuration for updating CAMUNDA_PLATFORM_VERSION

- docker-compose-web-modeler.yaml
Uses the environment variables recommended by https://docs.camunda.io/docs/self-managed/modeler/web-modeler/configuration/#database for configuring database connectivity.
Relates to https://github.com/camunda/web-modeler/issues/4457
> chore(web-modeler): switch to spring env vars for db config

- .github/workflows/test-release.yaml
We get a lot of renovate update changes relating to parts of the release notes script. I added a github actions workflow that will run the release notes script without updating anything just to test if a new version of a dependency breaks the script.
> fix: adds unit test for release script to simplify renovate updates

- .keycloak/Dockerfile
When building your own keycloak docker image on aarch64 architectures (commonly on m1 macs), running recently will throw an error:
```
ERROR: Failed to run 'build' command.
ERROR: Failed to update server configuration.
ERROR: Could not initialize class sun.util.calendar.ZoneInfoFile
For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```
While debugging, I noticed there was a missing symlink, and that the file that the symlink pointed to belongs to a package not installed on our docker image.  This PR adds that package, and provides that file.
To debug this, I created an aarch64 VM, since I do not own an M1 Mac, and then I ran 
```
DOCKER_BUILDKIT=0 docker build -t …
```
> Fix aarch64 keycloak

- README.md
For a better linking in other docs, introduce a headline and an anchor to the docker-compose-core description.
> Add headline to basic components

- .github/workflows/release.yaml
- release-notes-fetcher/release.sh
Release artifacts will now be uploaded to Operate repository instead of Zeebe repository. This PR updates the scripts accordingly.
> chore: fetch Operate artifacts from Operate repository instead of Zeebe

- .github/renovate.json5
These dependency upgrades for go-github are excessive, and violates typical versioning schemes, so renovate often outputs a PR that doesn't work.  Furthermore, theres no need to update this dependency until it stops working.
> Stop renovate from upgrading go-github

- .github/workflows/test-release.yaml
- release-notes-fetcher/fetch.go
This PR changes the way camunda-platform collects release notes from Operate, because in the future releases Operate will be pushing release notes to the individual releases (https://github.com/camunda/operate/releases) in the release body as seen in the screenshot below.
> chore: get release notes from operate release by tag instead of changelog

- .github/renovate.json5
I'm getting increasingly annoyed with the dependency updates for just a silly release notes script.  There's no risk for this script becoming out-of-date.
> fix: disables all renovate go updates

- .env
- README.md
- docker-compose.yaml
Using the changes I'm able to test Camunda 8 self-managed during development with [multi-tenancy](https://docs.camunda.io/docs/self-managed/concepts/multi-tenancy/) enabled.
> feat: support multi-tenancy enabled setup

- README.md
`keycloak` name is not exposed under normal circumstances, outside of the internal network.
> docs: introduce Desktop Modeler deployment

- docker-compose-core.yaml
- docker-compose.yaml
Readiness probe for Tasklist container always fails.
Since we have changed the base image of Tasklist to Alpine and `curl` is not installed by default in Alpine.
> refactor: use wget for Tasklist healthcheck

- docker-compose.yaml
Switch Connectors to the new authentication mechanism via Identity SDK.
`docker-compose-core` is not affected.
Depends on: https://github.com/camunda/connectors/pull/1847
Related to: https://github.com/camunda/connectors/issues/1638
> chore(connectors): switch to identity SDK config

- docker-compose-web-modeler.yaml
Related support ticket: https://jira.camunda.com/plugins/servlet/samlsso?redirectTo=%2Fbrowse%2FSUPPORT-20531
I added a volume to the modeler-db in order to preserve the diagrams that are created.
> Added volume to modeler-db to preserver diagrams

- docker-compose.yaml
Connectors should use the Operate audience to authenticate with Operate.
> fix(connectors): use correct audience for operate auth

- docker-compose-core.yaml
Change the restart policy of container zeebe and elasticsearch from always to unless-stopped.
With this change, the user can control when the cluster should be started and stopped explicitly. Cluster stop will survive a restart of Docker or the host computer.
For a development environment, where I have to take care of the resources, this should be sufficient.
If this pull request gets accepted, we can discuss if it is useful for the full docker-compose.yaml as well and if it should be mentioned in the readme.
> Restart containers unless stopped

- docker-compose.yaml
Operate and tasklist tried to validate the token via localhost which does not work in the docker network.
They have been adjusted to use the internal keycloak url
> spring security properties for operate and tasklist fixed

- .github/workflows/release.yaml
This should probably get backported to `stable/8.5` branch.
> fix: get Operate artifacts from monorepo starting with 8.5

- RELEASE.md
closes #101 
This PR adds documentation on how to release a version of this repository. 
This should also help ensure that the `.env` file gets updated with the latest alpha release if the release is an alpha.
> docs: adds release process

- docker-compose/camunda-8.6/.env
- docker-compose/camunda-8.6/README.md
- docker-compose/camunda-8.6/connector-secrets.txt
- docker-compose/camunda-8.6/docker-compose-core.yaml
- docker-compose/camunda-8.6/docker-compose.yaml
Needed to setup for a follow-up PR which implements: https://github.com/camunda/web-modeler/issues/9437
This PR introduces [compose profiles](https://docs.docker.com/compose/profiles/) to get rid of `docker-compose-web-modeler.yaml` and set up for the issue mentioned above.
> chore: add compose profiles for web modeler

- .env
- docker-compose/camunda-8.6/.env
- docker-compose/camunda-8.6/README.md
- docker-compose/camunda-8.6/docker-compose.yaml
Closes https://github.com/camunda/web-modeler/issues/9437.
This PR introduces the possibility to run web modeler stand alone with all needed dependencies (Identity + Keycloak) and uses the new public Docker Hub repositories for pulling Web Modeler images.
The `test-modeler.yaml` ci-test still needs to be adjusted to test the version in this `docker-compose/camunda-8.6` directory (only the docker-compose setup in the root directory gets tested). I could not get it done in a fixed time frame and should be done in a follow-up issue.
The Web Modeler version needs to be changed with the alpha2 release.
Final review should be done by Ahmed.
> feat: add web-modeler only setup

- .github/renovate.json5
- docker-compose/camunda-8.6/.env
Reverts the changes from [#671](https://github.com/camunda/camunda-platform/pull/671), [#668](https://github.com/camunda/camunda-platform/pull/668), and [#669](https://github.com/camunda/camunda-platform/pull/669).
See also this [Slack thread](https://camunda.slack.com/archives/C03NFMH4KC6/p1717749571220849).
> fix: use correct 8.6.0-alpha2 versions + disable Renovate auto-merge for release candidates

- .github/workflows/release-generation.yaml
- .github/workflows/release.yaml
- .github/workflows/test-release.yaml
- release-notes-fetcher/fetch.go
The recent change to move from repo `camunda/zeebe` to `camunda/camunda` means that the release notes fetcher should be looking at the new camunda repo for release notes.  Inside the camunda/camunda repo, operate releases are specified under the `operate-8.x.y` tag, so in this code change, operate will now append `operate-` to the tag name it's searching for.
> fix: use camunda/camunda repo for operate and zeebe

- .github/workflows/release-generation.yaml
- .github/workflows/release.yaml
- release-notes-fetcher/fetch.go
- release-notes-fetcher/go.mod
- release-notes-fetcher/go.sum
Adapting:
- release-generation should be triggered with the right pattern
- Operate to get from the correct repo depending on the version
> fix: adapting operate to get from the right repo

- .github/workflows/release-generation.yaml
- due to the single Jar there are no Operate-specific artifacts anymore
> Do not attempt to fetch Operate resources from the mono repo for >= 8.6

- .env
- docker-compose-core.yaml
- docker-compose.yaml
A large reason why components aren't getting auto-updated right now are because each component is still tied to eachother, so this PR will split this out.
> fix: separate component versions

- .env
- README.md
- docker-compose-web-modeler.yaml
- docker-compose.yaml
- docker-compose/camunda-8.6/.env
- docker-compose/camunda-8.6/docker-compose.yaml
I've seen a couple of instances both internal and external where the docker-compose in this repo isn't fully supportive of recent component changes relating to the Keycloak URLs used for token refresh and revoke.
This PR tries to bring them inline (testing locally shows success), but there are a couple of things to note:
- Identity uses the "frontend" or the `ISSUER_URL` of keycloak to perform token refresh and revoke
- To be able to resolve the URLs correctly two things need to happen
- The `KEYCLOAK_HOST` variable needs to be set to the container name of Keycloak, in this instance `keycloak`
- The local machine should be able to resolve `keycloak` to `127.0.0.1`
> fix: update docker compose to match identity url changes

- docker-compose-core.yaml
on main, we disabled the CSRF protection by introducing this pull request:
https://github.com/camunda/camunda-platform/pull/807/commits/80e16ad51eb2b714647bec577ec59aa661dea6be
However, this change is not backported to 8.5 which causes the recent issues with renovate not being able to update dependencies in stable/8.5.
> backport(8.5): disable operate and tasklist csrf (#712)

- .github/workflows/release-generation.yaml
- .github/workflows/release.yaml
- .github/workflows/test-release.yaml
This is a forward-port of #791 since I finally figured out how to use v2 with identity and the release-notes fetcher
> chore(deps): update tibdex/github-app-token action to v2

- .env
- docker-compose-core.yaml
Related to https://github.com/camunda-community-hub/spring-zeebe/issues/933
Theres an issue in spring-zeebe sdk which requires this additional env var set for 8.4
> fix: add baseUrl and CSRF flags to stable/8.4

- .github/workflows/template-deploy.yaml
- .github/workflows/test-core.yaml
- .github/workflows/test-default.yaml
- .github/workflows/test-modeler.yaml
- docker-compose/camunda-8.6/.optimize/environment-config.yaml
- docker-compose/camunda-8.6/docker-compose-core.yaml
- docker-compose/camunda-8.6/docker-compose.yaml
- e2e_tests/tests/web_modeler_login.spec.ts
Closes https://github.com/camunda/web-modeler/issues/9822
With https://github.com/camunda/web-modeler/issues/9437 I introduced a new folder `docker-compose/camunda-8.6` which is not part of the ci test pipeline. With this PR I extended the pipeline to also run tests in the directory.
> Add ci-tests for 8.6 directory

- release-notes-fetcher/config/release-notes-fetcher-camunda-8.2.yaml
- release-notes-fetcher/config/release-notes-fetcher-camunda-8.3.yaml
- release-notes-fetcher/config/release-notes-fetcher-camunda-8.4.yaml
- release-notes-fetcher/config/release-notes-fetcher-camunda-8.5.yaml
- release-notes-fetcher/config/release-notes-fetcher-camunda-8.6.yaml
the release notes fetcher is grabbing incorrect release notes due to the yaml files not having been updated.
> chore: update release-notes-fetcher versions

- .github/renovate.json5
closes: https://github.com/camunda/camunda-platform-helm/issues/2344
Use Renovatebot's new secrets syntax.
Now, the encrypted secret is saved in the renovatebot cloud service.
> chore: use renovatebot new secrets syntax

- README.md
- docker-compose/camunda-8.6/README.md
References the correct port for Zeebe clusters protected via Identity authentication
> fix(web-modeler): fix Keycloak URL for Web Modeler

- .env
Updating manually since Renovate did not automatically create a PR for the new version.
> chore(deps): update camunda/web-modeler docker tag to v8.5.12 (stable/8.5)

- .github/workflows/release-generation.yaml
As discussed in [Slack](https://camunda.slack.com/archives/C08MRKHJ0CD/p1746517143674509)
Tasklist artifacts are not always pulled into camunda-platform releases for pre 8.6 versions
The problem is that the workflow is assuming that Zeebe and Tasklist have the same versions, which is not always true
> fix: use correct Tasklist version in release-generation
