docker-compose.yaml

Sets CAMUNDA_OPTIMIZE_UI_LOGOUT_HIDDEN to true
Came up in helm chart PR https://github.com/camunda/camunda-platform-helm/pull/287#discussion_r855299140 was raised by @RomanJRW 
See https://docs.camunda.io/docs/self-managed/platform-deployment/docker/#optimize
> Disables the logout button (logout is handled by Identity).

Hide logout for optimize

---

README.md

Update README to clarify that Zeebe is not a HTTP application
related with #9

Clarify Zeebe is not HTTP application

---

README.md

* I propose to reference the Modeler so that readers of this guide can more quickly and easier can get started using Camunda 8

chore(README): reference Camunda Desktop Modeler

---

README.md
docker-compose-web-modeler-beta.yaml
docker-compose.yaml

32 modeler developer preview

---

docker-compose-core.yaml
docker-compose.yaml

Bump connector-bundle due to AWS Lambda bug-fix.

chore: update connectors-bundle to 0.1.1

---

README.md

docs: describe Connector template installation

---

README.md
docker-compose.yaml

feat: upgrade keycloak version to 19.0.3 in docker-compose

---

README.md
docker-compose-core.yaml
docker-compose.yaml

⚠️ Only merge when Connectors 0.2.0 is available.

feat: bump Connectors to 0.2.0

---

docker-compose-web-modeler-beta.yaml

Relates to camunda/web-modeler#3000

chore: bump Web Modeler to 0.2.0-beta

---

docker-compose-web-modeler-beta.yaml

Relates to https://github.com/camunda/web-modeler/issues/3049

chore: bump Web Modeler to 0.2.1-beta

---

docker-compose-web-modeler-beta.yaml

related to https://github.com/camunda/web-modeler/issues/2973

chore(docker-compose): add public API audience

---

docker-compose-web-modeler-beta.yaml

Relates to https://github.com/camunda/web-modeler/issues/3363

chore(docker-compose): configure mail sender address for Web Modeler

---

docker-compose-core.yaml
docker-compose.yaml

- Core: working
- Full package: disabling inbound polling for the time-being until I figure out how to connect it to the Keycloak

deps: bump connectors-bundle

---

docker-compose-web-modeler-beta.yaml

see https://github.com/camunda/web-modeler/issues/3443

chore(docker-compose): update Web Modeler to 0.4.0-beta

---

docker-compose-web-modeler-beta.yaml
docker-compose.yaml

Updates to latest version of Web Modeler.
Closes #85.

Web Modeler 0.5.0 beta

---

docker-compose-core.yaml
docker-compose.yaml

Bump connectors version to the newly released 0.17.0

chore(connectors): bump connectors-bundle to 0.17.1

---

docker-compose-core.yaml

Added ports to core yaml file to be consistent with main yaml file

Added ports to connectors to expose inbound webhook connector

---

.github/renovate.json5

Enables automerge for minor/patch dependencies if the builds/tests pass.

feat(ci): enable automerge

---

.github/renovate.json5

I added rules so that stable versions will still get patch updates.

fix: improved renovate for stable/8.1 and stable/8.2 dependencies

---

.env

https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/values/values-v8.2.yaml

fix: updated optimize and connectors to match helm chart versions

---

.github/renovate.json5

Follow-up PR after review of https://github.com/camunda/camunda-platform/pull/389#pullrequestreview-1740310706

improve: reorder allowed version conditions by component

---

docker-compose-web-modeler.yaml

Part of https://github.com/camunda/web-modeler/issues/6719.

chore(web-modeler): add SERVER_HTTPS_ONLY environment variable

---

docker-compose-web-modeler.yaml

chore(web-modeler): add SERVER_HTTPS_ONLY environment variable (#411)

---

.github/workflows/add-to-project.yml

related to https://github.com/camunda/distribution/issues/161

chore: added GH app token in add-to-project workflow

---

.env
docker-compose-web-modeler.yaml

Part of https://github.com/camunda/web-modeler/issues/7077

chore(web-modeler): adjust env variables for OIDC configuration scheme

---

docker-compose-core.yaml
docker-compose.yaml

backports https://github.com/camunda/camunda-platform/pull/451

refactor: use wget for Tasklist healthcheck

---

docker-compose.yaml

bugfix: jwt params for Operate and Tasklist

---

.env

Update Core components' version to 8.5.0. All other components are updated by renovate.

Update .env to 8.5.0

---

release-notes-fetcher/config/release-notes-fetcher-camunda-8.5.yaml
release-notes-fetcher/config/release-notes-fetcher-camunda-8.6.yaml

add fiels needed for release notes fetcher for 8.5 and 8.6 releases

chore: allow platform release to work with different component versions

---

docker-compose-web-modeler.yaml

Relates to https://github.com/camunda/web-modeler/issues/9521

feat(web-modeler): use dedicated health endpoints

---

docker-compose-web-modeler.yaml

Backports https://github.com/camunda/camunda-platform/pull/623 to `8.4`

chore(web-modeler): add websockets health endpoint

---

docker-compose/camunda-8.6/README.md

Small clarification after https://github.com/camunda/camunda-docs/pull/3887 and https://github.com/camunda/camunda-docs/pull/3858 are live.

chore(web-modeler): clarify non-production restrictions

---

release-notes-fetcher/config/release-notes-fetcher-camunda-8.2.yaml
release-notes-fetcher/config/release-notes-fetcher-camunda-8.3.yaml
release-notes-fetcher/config/release-notes-fetcher-camunda-8.4.yaml
release-notes-fetcher/config/release-notes-fetcher-camunda-8.5.yaml
release-notes-fetcher/config/release-notes-fetcher-camunda-8.6.yaml

Bumping versions for release notes generations

chore: bumping versions for release notes

---

release-notes-fetcher/config/release-notes-fetcher-camunda-8.3.yaml
release-notes-fetcher/config/release-notes-fetcher-camunda-8.4.yaml
release-notes-fetcher/config/release-notes-fetcher-camunda-8.5.yaml

To publish the new Operate patch

chore: update versions for release note fetcher

---

docker-compose-core.yaml

csrf protection is not required in a local setup.

disable operate and tasklist csrf

---

.github/workflows/release-generation.yaml

Adding a new pattern so this is also triggered

fix: adding new pattern to release-generation

---

.github/workflows/release-generation.yaml
release-notes-fetcher/config/release-notes-fetcher-camunda-8.4.yaml
release-notes-fetcher/fetch.go
release-notes-fetcher/go.mod
release-notes-fetcher/go.sum
release-notes-fetcher/release-notes-template.txt

Backporting fixes for release notes to 8.4

fix: fixing release notes for 8.4

---

docker-compose/camunda-8.6/docker-compose.yaml

Relates to https://github.com/camunda/web-modeler/pull/10562#issuecomment-2307396585

fix(web-modeler): use correct token audience

---

docker-compose.yaml
docker-compose/camunda-8.6/docker-compose.yaml

possibly related https://github.com/camunda/camunda-platform/issues/838

fix: identity now works on separate docker server

---

.env

Update 8.4+gen13 component versions

---

.env

FYI: [Renovate configurations](https://github.com/camunda/camunda-platform/blob/main/.github/renovate.json5) for the `stable/8.5` branch are missing, so I'm creating this PR manually.

chore(deps): update Web Modeler to v8.5.10

---

.env

Update Web Modeler to latest patch version.

chore(deps): update Web Modeler to v8.5.11

---

docker-compose/camunda-8.6/README.md
docker-compose/camunda-8.6/docker-compose-full.yaml
docker-compose/camunda-8.6/docker-compose-web-modeler.yaml
docker-compose/camunda-8.6/docker-compose.yaml

Adding a new definition that deploys all Camunda 8 components

adding to new definition to replace full profile

---

README.md
docker-compose/camunda-8.6/README.md

Several Changes to normalize and improve this repository to fix several inconsistencies

Adding several improvements to readme

---

docker-compose-web-modeler.yaml
docker-compose/camunda-8.6/docker-compose-full.yaml
docker-compose/camunda-8.6/docker-compose-web-modeler.yaml
docker-compose/camunda-8.6/docker-compose.yaml

Part of camunda/web-modeler#5137

chore(web-modeler): remove unused env
